// IMPORTANT: PASTE YOUR GOOGLE APPS SCRIPT WEB APP URL HERE
// PENTING: TEMPELKAN URL WEB APP GOOGLE APPS SCRIPT ANDA DI SINI

// Example: 'https://script.google.com/macros/s/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/exec'
export const GOOGLE_APPS_SCRIPT_URL = 'https://script.google.com/macros/s/AKfycbwDbzGQDl9qgJcQKjVJLODV53SINlm3xJwF0rQK3-jzjS5Kv2D4PGCw8_YMW3cDQhcYyg/exec';